version: '3.3'
volumes:
  gitclassroom_mongo:
services:
  gitclassroom-mongo:
    image: library/mongo:4
    ports:
      - '9007:27017'
    volumes:
      - 'gitclassroom_mongo:/data/db'
  gitclassroom-service:
    build: .
    image: gitclassroom-service
    volumes:
      - type: bind
        source: ./
        target: /app
    command: ['thin','start','-e','development']
    ports:
      - '8100:3000'
